package IL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptBusinessConcept = new ConceptDescriptorBuilder("IL.structure.BusinessConcept", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f42182L)).super_("IL.structure.Concept").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L)).parents("IL.structure.Concept").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L)).create();
  /*package*/ final ConceptDescriptor myConceptBusinessFact = new ConceptDescriptorBuilder("IL.structure.BusinessFact", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f47e24L)).super_("IL.structure.Concept").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L)).parents("IL.structure.Concept").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptBusinessTerm = new ConceptDescriptorBuilder("IL.structure.BusinessTerm", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptCharacteristic = new ConceptDescriptorBuilder("IL.structure.Characteristic", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d13eL)).super_("IL.structure.BusinessFact").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f47e24L)).parents("IL.structure.BusinessFact").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f47e24L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4995452815073475988L, "representsAspectOf", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f42182L), true)).references("representsAspectOf").create();
  /*package*/ final ConceptDescriptor myConceptConcept = new ConceptDescriptorBuilder("IL.structure.Concept", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptPreferredTerm = new ConceptDescriptorBuilder("IL.structure.PreferredTerm", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9fc649cL)).super_("IL.structure.BusinessTerm").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).parents("IL.structure.BusinessTerm").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).childDescriptors(new ConceptDescriptorBuilder.Link(2520760728231371933L, "preferredTermFor", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L), false, false, false)).children(new String[]{"preferredTermFor"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptRelation = new ConceptDescriptorBuilder("IL.structure.Relation", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d142L)).super_("IL.structure.BusinessFact").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f47e24L)).parents("IL.structure.BusinessFact").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f47e24L)).create();
  /*package*/ final ConceptDescriptor myConceptSpecification = new ConceptDescriptorBuilder("IL.structure.Specification", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9c0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(2520760728230877633L, "Statements", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9fddb5dL), true, true, false)).children(new String[]{"Statements"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptStatement = new ConceptDescriptorBuilder("IL.structure.Statement", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9fddb5dL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(2520760728231467872L, "terms", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L), true, true, false)).children(new String[]{"terms"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptSynonym = new ConceptDescriptorBuilder("IL.structure.Synonym", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9fc64a1L)).super_("IL.structure.BusinessTerm").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).parents("IL.structure.BusinessTerm").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(2520760728231371938L, "isSynonymFor", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d9e0L), false)).references("isSynonymFor").create();
  /*package*/ final ConceptDescriptor myConceptWord = new ConceptDescriptorBuilder("IL.structure.Word", MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x455369de469f89c4L)).super_("IL.structure.BusinessTerm").super_(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).parents("IL.structure.BusinessTerm").parentIds(MetaIdFactory.conceptId(0x31cb0177ae9c4868L, 0xafb61ac48c69379dL, 0x22fb8a86d9f4d143L)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBusinessConcept, myConceptBusinessFact, myConceptBusinessTerm, myConceptCharacteristic, myConceptConcept, myConceptPreferredTerm, myConceptRelation, myConceptSpecification, myConceptStatement, myConceptSynonym, myConceptWord);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0p, conceptFqName)) {
      case 0:
        return myConceptBusinessConcept;
      case 1:
        return myConceptBusinessFact;
      case 2:
        return myConceptBusinessTerm;
      case 3:
        return myConceptCharacteristic;
      case 4:
        return myConceptConcept;
      case 5:
        return myConceptPreferredTerm;
      case 6:
        return myConceptRelation;
      case 7:
        return myConceptSpecification;
      case 8:
        return myConceptStatement;
      case 9:
        return myConceptSynonym;
      case 10:
        return myConceptWord;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0p = new String[]{"IL.structure.BusinessConcept", "IL.structure.BusinessFact", "IL.structure.BusinessTerm", "IL.structure.Characteristic", "IL.structure.Concept", "IL.structure.PreferredTerm", "IL.structure.Relation", "IL.structure.Specification", "IL.structure.Statement", "IL.structure.Synonym", "IL.structure.Word"};
}
