package IL.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new BusinessConcept_BehaviorDescriptor();
      case 1:
        return new Characteristic_BehaviorDescriptor();
      case 3:
        return new Relation_BehaviorDescriptor();
      case 4:
        return new Specification_BehaviorDescriptor();
      case 2:
        return new PreferredTerm_BehaviorDescriptor();
      case 6:
        return new Synonym_BehaviorDescriptor();
      case 5:
        return new Statement_BehaviorDescriptor();
      case 7:
        return new Word_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"IL.structure.BusinessConcept", "IL.structure.Characteristic", "IL.structure.PreferredTerm", "IL.structure.Relation", "IL.structure.Specification", "IL.structure.Statement", "IL.structure.Synonym", "IL.structure.Word"};
}
