package IL.behavior;

/*Generated by MPS */


public abstract class BusinessFact_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public BusinessFact_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.BusinessFact";
  }
}
