package IL.behavior;

/*Generated by MPS */


public class BusinessConcept_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public BusinessConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.BusinessConcept";
  }
}
