package IL.behavior;

/*Generated by MPS */


public class Characteristic_BehaviorDescriptor extends BusinessFact_BehaviorDescriptor {
  public Characteristic_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.Characteristic";
  }
}
