package IL.behavior;

/*Generated by MPS */


public class PreferredTerm_BehaviorDescriptor extends BusinessTerm_BehaviorDescriptor {
  public PreferredTerm_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.PreferredTerm";
  }
}
