package IL.behavior;

/*Generated by MPS */


public class Relation_BehaviorDescriptor extends BusinessFact_BehaviorDescriptor {
  public Relation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.Relation";
  }
}
