package IL.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Statement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Statement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.Statement";
  }
}
