package IL.behavior;

/*Generated by MPS */


public class Synonym_BehaviorDescriptor extends BusinessTerm_BehaviorDescriptor {
  public Synonym_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.Synonym";
  }
}
