package IL.behavior;

/*Generated by MPS */


public class Word_BehaviorDescriptor extends BusinessTerm_BehaviorDescriptor {
  public Word_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "IL.structure.Word";
  }
}
